backend:
  name: git-gateway
  branch: dev
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - label: 'List of Chapters'
    name: 'list_of_chapters'
    identifier_field: name
    description:
      'Перелік розділів. При зміні уже існуючих розділів потрібно повторно
      обрати їх у вже існуючих колекціях (наприклад, Chapters_UA)'
    folder: 'content/list-of-chapters'
    create: true
    delete: false
    path: 'list-of-chapters'
    fields:
      [
        {
          label: 'Title at page',
          name: 'title',
          widget: 'string',
          required: true,
        },
        {
          label: 'chapter item',
          name: 'chapter_item',
          widget: 'list',
          fields:
            [
              {
                label: 'chapter name',
                name: 'chapter_name',
                widget: string,
                required: true,
                pattern:
                  [
                    '^[a-z]+[a-z0-9-]+[-]*[a-z0-9-]*[a-z0-9]+$',
                    'Назва може містити тільки малі латинські літери, цифри та
                    тире. Має починатися з літери та не може закінчуватися на
                    тире',
                  ],
              },
            ],
        },
      ]
  - label: 'List of Subheads'
    name: 'list_of_subheads'
    identifier_field: subhead_value
    description:
      'Перелік підрозділів. При зміні уже існуючих підрозділів потрібно повторно
      обрати їх у вже існуючих колекціях (наприклад, Chapters_UA)'
    folder: 'content/list-of-subheads'
    create: true
    delete: false
    path: 'list-of-subheads'
    fields:
      [
        {
          label: 'Title at page',
          name: 'title',
          widget: 'string',
          required: true,
        },
        {
          label: 'subhead item',
          name: 'subhead_item',
          widget: 'list',
          fields:
            [
              {
                label: 'subhead value',
                name: 'subhead_value',
                widget: string,
                required: true,
                pattern:
                  [
                    '^[a-z]+[a-z0-9-]+[-]*[a-z0-9-]*[a-z0-9]+$',
                    'Назва може містити тільки малі латинські літери, цифри та
                    тире. Має починатися з літери та не може закінчуватися на
                    тире',
                  ],
              },
              {
                label: 'Subhead at page, ua',
                name: 'subhead_ua',
                widget: string,
                required: true,
              },
              {
                label: 'Subhead at page, ru',
                name: 'subhead_ru',
                widget: string,
                required: true,
              },
              {
                label: 'Subhead range',
                name: 'subhead_range',
                widget: 'string',
                required: false,
                pattern:
                  [
                    '^[0-9]{1,2}$',
                    'Може містити тільки цифри, що позначають черговість
                    розміщення підзаголовка на веб-сторінці (зверху вниз)',
                  ],
              },
            ],
        },
      ]
  - label: 'Chapters_RU'
    name: 'chapters_ru'
    folder: 'content/chapters'
    label_singular: 'Chapters_RU'
    slug: '{{fields.slug}}'
    description:
      'Разделы на русском языке. Для создания нового раздела, пожалуйста,
      сначала добавьте его в коллекцию List of Chapters'
    create: true
    delete: true
    path: '{{chapter}}/{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - {
          label: 'Chapter',
          name: 'chapter',
          collection: 'list_of_chapters',
          widget: 'relation',
          required: true,
          search_fields: ['chapter_item.*.chapter_name'],
          value_field: 'chapter_item.*.chapter_name',
          display_fields: ['chapter_item.*.chapter_name'],
        }
      - {
          label: 'Title at page',
          name: 'title',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - {
          label: 'Subhead',
          name: 'subhead',
          widget: 'list',
          fields:
            [
              {
                label: 'Subhead title',
                name: 'subhead_title',
                collection: 'list_of_subheads',
                widget: 'relation',
                required: true,
                search_fields: ['subhead_item.*.subhead_ru'],
                value_field: 'subhead_item.*.subhead_ru',
                display_fields: ['subhead_item.*.subhead_ru'],
              },
              {
                label: 'Questions',
                name: 'questions',
                widget: 'list',
                fields:
                  [
                    {
                      label: Question title,
                      name: question_title,
                      widget: markdown,
                      editor_components: ['code-block'],
                      required: true,
                    },
                    {
                      label: Description,
                      name: description,
                      widget: 'markdown',
                      required: true,
                    },
                    {
                      label: 'Question range',
                      name: 'question_range',
                      widget: 'string',
                      required: false,
                      pattern:
                        [
                          '^[0-9]{1,2}$',
                          'Может содержать только цифры, обозначающие
                          очередность размещение вопроса на веб-странице (сверху
                          вниз)',
                        ],
                    },
                  ],
              },
            ],
        }
  - label: 'Chapters_UA'
    name: 'chapters_ua'
    folder: 'content/chapters'
    label_singular: 'Chapters_UA'
    slug: '{{fields.chapter}}'
    description:
      'Розділи українською мовою. Для створення нового розділу, будь ласка,
      спочатку додайте його в колекцію List of Chapters'
    create: true
    delete: true
    path: '{{chapter}}/{{language}}'
    filter: { field: 'language', value: 'ua' }
    fields:
      - {
          label: 'Chapter',
          name: 'chapter',
          collection: 'list_of_chapters',
          widget: 'relation',
          required: true,
          search_fields: ['chapter_item.*.chapter_name'],
          value_field: 'chapter_item.*.chapter_name',
          display_fields: ['chapter_item.*.chapter_name'],
        }
      - {
          label: 'Title at page',
          name: 'title',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ua'],
          default: 'ua',
        }
      - {
          label: 'Subhead',
          name: 'subhead',
          widget: 'list',
          required: true,
          fields:
            [
              {
                label: 'Subhead title',
                name: 'subhead_title',
                collection: 'list_of_subheads',
                widget: 'relation',
                required: true,
                search_fields: ['subhead_item.*.subhead_ua'],
                value_field: 'subhead_item.*.subhead_ua',
                display_fields: ['subhead_item.*.subhead_ua'],
              },
              {
                label: 'Questions',
                name: 'questions',
                widget: 'list',
                fields:
                  [
                    {
                      label: Question title,
                      name: question_title,
                      widget: markdown,
                      editor_components: ['code-block'],
                      required: true,
                    },
                    {
                      label: Description,
                      name: description,
                      widget: 'markdown',
                      required: true,
                    },
                    {
                      label: 'Question range',
                      name: 'question_range',
                      widget: 'string',
                      required: false,
                      pattern:
                        [
                          '^[0-9]{1,2}$',
                          'Може містити тільки цифри, що позначають черговість
                          розміщення питання на веб-сторінці (зверху вниз)',
                        ],
                    },
                  ],
              },
            ],
        }
